### ISSUE TITLE
Using compoxture with JS / CSS (without CDN)

### ISSUE THREAD

**Issue by DenisBiondic** [tes/compoxure#111]
Hi,

I think compoxture has a architectural affinity towards using CDN approach with Bosco, and I find it a bit difficult to figure out how far can Compoxture help when using JS / CSS without CDN. It can also be that my understanding of your comment "you should always use CDN" is limited, because I don't see how can this fit with also working locally wihout CDN, etc.

I think some examples would be helpful, showcasing couple of services with not only HTML but CSS / JS as well. 

One of the key problems (or questions) that I see in my head is each service delivering CSS / JS in different slots (because we don't want stylesheets in middle of our HTML) and figuring out how to effectively cache it all at once. A similar problem with can be solved when using Nginx SSI + page speed module which bundles all the static files and caches them together.

I would also be happy to help out with examples / pull requests if I get a bit more undestanding.

P.S. great work on the library 👍

**Comment by cliftonc** [comment]
@DenisBiondic apologies for the delay, we missed this.

From Compoxure's perspective CDN just means a http server that serves assets, it doesn't need to be an actual CDN, it can point back at your application.

It is however (if you use the `cx-bundles` directive) very opinionated about the structure of the js/css files on that server, which is what bosco helps tie together for you.  The `cx-bundles` directive is specifically designed (and separate) to `cx-url` so that you can include the service HTML fragments in the page wherever you like, but include the CSS/JS in the head, with server-push etc. if you want.

The best working full example is here:  https://github.com/tes/compoxure-example

If you visit tes.com, and view the page source, you will see how we use it - just search for `cx-bundles` or `cx-url`.

e.g. https://www.tes.com/teaching-resource/nine-tails-pirate-song-11747533

**Comment by ksnll** [comment]
We're closing this for now, if you need any further information let us know
